package com.genai.jmeter.plugin.generator;

import com.genai.jmeter.plugin.correlate.CorrelationDecision;
import com.genai.jmeter.plugin.har.HARModel;
import com.genai.jmeter.plugin.scanner.DynamicValue;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates production-ready JMeter JMX scripts from HAR entries + correlation decisions.
 */
public class JMXGenerator {

    private static final Logger log = LoggerFactory.getLogger(JMXGenerator.class);

    private String testPlanName = "GenAI Correlated Test Plan";
    private String threadGroupName = "Thread Group";
    private int numThreads = 1;
    private int rampUp = 1;
    private int loops = 1;

    public JMXGenerator withTestPlanName(String name) { this.testPlanName = name; return this; }
    public JMXGenerator withThreads(int threads, int rampUp, int loops) {
        this.numThreads = threads; this.rampUp = rampUp; this.loops = loops; return this;
    }

    /**
     * Generates JMX XML string from entries and correlation decisions.
     */
    public String generate(List<HARModel.Entry> entries, List<CorrelationDecision> decisions) {
        Map<String, List<CorrelationDecision>> extractorsByEntry = groupByEntry(decisions);

        StringBuilder jmx = new StringBuilder();
        jmx.append(xmlHeader());
        jmx.append(testPlanOpen());
        jmx.append(hashTreeOpen());
        jmx.append(threadGroupOpen());
        jmx.append(hashTreeOpen());

        // CSV Data Set Config placeholder for parameterization
        jmx.append(csvDataSetPlaceholder());

        // HTTP Request Defaults
        String baseDomain = extractBaseDomain(entries);
        jmx.append(httpDefaults(baseDomain));

        // Cookie Manager
        jmx.append(cookieManager());

        // Cache Manager
        jmx.append(cacheManager());

        // Header Manager
        jmx.append(headerManager(entries));

        // Samplers
        for (int i = 0; i < entries.size(); i++) {
            HARModel.Entry entry = entries.get(i);
            String idx = String.valueOf(i);
            List<CorrelationDecision> entryExtractors = extractorsByEntry.getOrDefault(idx, Collections.emptyList());
            jmx.append(httpSampler(entry, i, entryExtractors, decisions));
            jmx.append(hashTreeOpen());

            // Add extractors that fire from this entry's response
            for (CorrelationDecision decision : entryExtractors) {
                if (!decision.shouldSkip()) {
                    jmx.append(extractorElement(decision));
                }
            }

            jmx.append(hashTreeClose()); // sampler children
        }

        // Result collectors
        jmx.append(viewResultsTree());
        jmx.append(summaryReport());

        jmx.append(hashTreeClose()); // thread group children
        jmx.append(hashTreeClose()); // thread group
        jmx.append(hashTreeClose()); // test plan children
        jmx.append(hashTreeClose()); // test plan
        jmx.append(jmeterTestPlanClose());

        return jmx.toString();
    }

    public void saveToFile(String jmxContent, File outputFile) throws IOException {
        Files.writeString(outputFile.toPath(), jmxContent, StandardCharsets.UTF_8);
        log.info("JMX saved to {}", outputFile.getAbsolutePath());
    }

    // ─── JMX element builders ─────────────────────────────────────────────────

    private String xmlHeader() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    }

    private String testPlanOpen() {
        return "<jmeterTestPlan version=\"1.2\" properties=\"5.0\" jmeter=\"5.6.3\">\n" +
                "  <hashTree>\n" +
                "    <TestPlan guiclass=\"TestPlanGui\" testclass=\"TestPlan\" testname=\"" + esc(testPlanName) + "\" enabled=\"true\">\n" +
                "      <stringProp name=\"TestPlan.comments\">Generated by GenAI JMeter Plugin</stringProp>\n" +
                "      <boolProp name=\"TestPlan.functional_mode\">false</boolProp>\n" +
                "      <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>\n" +
                "      <elementProp name=\"TestPlan.user_defined_variables\" elementType=\"Arguments\">\n" +
                "        <collectionProp name=\"Arguments.arguments\"/>\n" +
                "      </elementProp>\n" +
                "    </TestPlan>\n";
    }

    private String threadGroupOpen() {
        return "    <ThreadGroup guiclass=\"ThreadGroupGui\" testclass=\"ThreadGroup\" testname=\"" + esc(threadGroupName) + "\" enabled=\"true\">\n" +
                "      <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>\n" +
                "      <elementProp name=\"ThreadGroup.main_controller\" elementType=\"LoopController\">\n" +
                "        <boolProp name=\"LoopController.continue_forever\">false</boolProp>\n" +
                "        <stringProp name=\"LoopController.loops\">" + loops + "</stringProp>\n" +
                "      </elementProp>\n" +
                "      <stringProp name=\"ThreadGroup.num_threads\">" + numThreads + "</stringProp>\n" +
                "      <stringProp name=\"ThreadGroup.ramp_time\">" + rampUp + "</stringProp>\n" +
                "      <boolProp name=\"ThreadGroup.scheduler\">false</boolProp>\n" +
                "    </ThreadGroup>\n";
    }

    private String csvDataSetPlaceholder() {
        return "      <!-- Add CSV Data Set Config here for parameterization -->\n";
    }

    private String httpDefaults(String baseDomain) {
        String scheme = "https", host = "", port = "";
        try {
            if (!baseDomain.isEmpty()) {
                URI uri = new URI(baseDomain);
                scheme = uri.getScheme();
                host = uri.getHost();
                port = uri.getPort() > 0 ? String.valueOf(uri.getPort()) : "";
            }
        } catch (URISyntaxException ignored) {}

        return "      <ConfigTestElement guiclass=\"HttpDefaultsGui\" testclass=\"ConfigTestElement\" testname=\"HTTP Request Defaults\" enabled=\"true\">\n" +
                "        <stringProp name=\"HTTPSampler.domain\">" + esc(host) + "</stringProp>\n" +
                "        <stringProp name=\"HTTPSampler.port\">" + port + "</stringProp>\n" +
                "        <stringProp name=\"HTTPSampler.protocol\">" + scheme + "</stringProp>\n" +
                "        <stringProp name=\"HTTPSampler.path\"></stringProp>\n" +
                "        <stringProp name=\"HTTPSampler.implementation\">HttpClient4</stringProp>\n" +
                "        <stringProp name=\"HTTPSampler.connect_timeout\">10000</stringProp>\n" +
                "        <stringProp name=\"HTTPSampler.response_timeout\">30000</stringProp>\n" +
                "      </ConfigTestElement>\n" +
                "      <hashTree/>\n";
    }

    private String cookieManager() {
        return "      <CookieManager guiclass=\"CookiePanel\" testclass=\"CookieManager\" testname=\"HTTP Cookie Manager\" enabled=\"true\">\n" +
                "        <boolProp name=\"CookieManager.clearEachIteration\">true</boolProp>\n" +
                "        <stringProp name=\"CookieManager.implementation\">org.apache.jmeter.protocol.http.control.HC4CookieHandler</stringProp>\n" +
                "      </CookieManager>\n" +
                "      <hashTree/>\n";
    }

    private String cacheManager() {
        return "      <CacheManager guiclass=\"CacheManagerGui\" testclass=\"CacheManager\" testname=\"HTTP Cache Manager\" enabled=\"true\">\n" +
                "        <boolProp name=\"clearEachIteration\">true</boolProp>\n" +
                "      </CacheManager>\n" +
                "      <hashTree/>\n";
    }

    private String headerManager(List<HARModel.Entry> entries) {
        // Collect common headers from first entry
        Set<String> commonHeaders = new LinkedHashSet<>();
        if (!entries.isEmpty() && entries.get(0).request.headers != null) {
            entries.get(0).request.headers.stream()
                    .filter(h -> isCommonHeader(h.name))
                    .forEach(h -> commonHeaders.add(h.name + "=" + h.value));
        }

        StringBuilder sb = new StringBuilder();
        sb.append("      <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Header Manager\" enabled=\"true\">\n");
        sb.append("        <collectionProp name=\"HeaderManager.headers\">\n");
        for (String header : commonHeaders) {
            String[] parts = header.split("=", 2);
            if (parts.length == 2) {
                sb.append("          <elementProp name=\"\" elementType=\"Header\">\n");
                sb.append("            <stringProp name=\"Header.name\">").append(esc(parts[0])).append("</stringProp>\n");
                sb.append("            <stringProp name=\"Header.value\">").append(esc(parts[1])).append("</stringProp>\n");
                sb.append("          </elementProp>\n");
            }
        }
        sb.append("        </collectionProp>\n");
        sb.append("      </HeaderManager>\n");
        sb.append("      <hashTree/>\n");
        return sb.toString();
    }

    private String httpSampler(HARModel.Entry entry, int idx,
            List<CorrelationDecision> extractors, List<CorrelationDecision> allDecisions) {

        String url = entry.request.url;
        String path = "/", host = "", queryString = "";
        try {
            URI uri = new URI(url);
            path = uri.getRawPath() != null ? uri.getRawPath() : "/";
            host = uri.getHost() != null ? uri.getHost() : "";
            queryString = uri.getRawQuery() != null ? uri.getRawQuery() : "";
        } catch (URISyntaxException ignored) {}

        String name = entry.request.method + " " + path;

        StringBuilder sb = new StringBuilder();
        sb.append("      <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"")
                .append(esc(name)).append("\" enabled=\"true\">\n");
        sb.append("        <stringProp name=\"HTTPSampler.method\">").append(esc(entry.request.method)).append("</stringProp>\n");
        sb.append("        <stringProp name=\"HTTPSampler.path\">").append(esc(applySubstitutions(path, idx, allDecisions))).append("</stringProp>\n");
        sb.append("        <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\n");
        sb.append("        <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\n");
        sb.append("        <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\n");

        // Query parameters
        sb.append("        <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\">\n");
        sb.append("          <collectionProp name=\"Arguments.arguments\">\n");
        if (entry.request.queryString != null) {
            for (HARModel.NameValuePair q : entry.request.queryString) {
                String val = applySubstitutions(q.value, idx, allDecisions);
                sb.append("            <elementProp name=\"").append(esc(q.name)).append("\" elementType=\"HTTPArgument\">\n");
                sb.append("              <boolProp name=\"HTTPArgument.always_encode\">true</boolProp>\n");
                sb.append("              <stringProp name=\"Argument.name\">").append(esc(q.name)).append("</stringProp>\n");
                sb.append("              <stringProp name=\"Argument.value\">").append(esc(val)).append("</stringProp>\n");
                sb.append("              <stringProp name=\"Argument.metadata\">=</stringProp>\n");
                sb.append("            </elementProp>\n");
            }
        }
        sb.append("          </collectionProp>\n");
        sb.append("        </elementProp>\n");

        // POST body
        if (entry.request.postData != null && entry.request.postData.text != null) {
            String body = applySubstitutions(entry.request.postData.text, idx, allDecisions);
            sb.append("        <boolProp name=\"HTTPSampler.postBodyRaw\">true</boolProp>\n");
            // Raw body is already handled in Arguments above with empty name
        }

        // Request-specific headers (auth, content-type, etc.)
        if (entry.request.headers != null) {
            entry.request.headers.stream()
                    .filter(h -> !isCommonHeader(h.name) && isImportantHeader(h.name))
                    .forEach(h -> {
                        String val = applySubstitutions(h.value, idx, allDecisions);
                        sb.append("        <!-- Header: ").append(esc(h.name)).append(": ").append(esc(val)).append(" -->\n");
                    });
        }

        // Response assertion for non-2xx
        sb.append("        <!-- Expected response: ").append(entry.response != null ? entry.response.status : "?").append(" -->\n");
        sb.append("      </HTTPSamplerProxy>\n");
        return sb.toString();
    }

    private String extractorElement(CorrelationDecision decision) {
        return switch (decision.getExtractorType()) {
            case REGEX -> regexExtractor(decision);
            case JSON_PATH -> jsonPathExtractor(decision);
            case XPATH -> xpathExtractor(decision);
            case BOUNDARY -> boundaryExtractor(decision);
            case GROOVY -> groovyExtractor(decision);
            default -> "<!-- SKIP: " + decision.getVariableName() + " -->\n";
        };
    }

    private String regexExtractor(CorrelationDecision d) {
        return "        <RegexExtractor guiclass=\"RegexExtractorGui\" testclass=\"RegexExtractor\" testname=\"Extract: " + esc(d.getVariableName()) + "\" enabled=\"true\">\n" +
                "          <stringProp name=\"RegexExtractor.useHeaders\">false</stringProp>\n" +
                "          <stringProp name=\"RegexExtractor.refname\">" + esc(d.getVariableName()) + "</stringProp>\n" +
                "          <stringProp name=\"RegexExtractor.regex\">" + esc(d.getExtractorExpression()) + "</stringProp>\n" +
                "          <stringProp name=\"RegexExtractor.template\">$1$</stringProp>\n" +
                "          <stringProp name=\"RegexExtractor.default\">EXTRACTION_FAILED</stringProp>\n" +
                "          <stringProp name=\"RegexExtractor.match_no\">1</stringProp>\n" +
                "        </RegexExtractor>\n" +
                "        <hashTree/>\n";
    }

    private String jsonPathExtractor(CorrelationDecision d) {
        return "        <JSONPathExtractor guiclass=\"JSONPathExtractorGui\" testclass=\"JSONPathExtractor\" testname=\"Extract: " + esc(d.getVariableName()) + "\" enabled=\"true\">\n" +
                "          <stringProp name=\"JSONPathExtractor.referenceNames\">" + esc(d.getVariableName()) + "</stringProp>\n" +
                "          <stringProp name=\"JSONPathExtractor.jsonPathExprs\">" + esc(d.getExtractorExpression()) + "</stringProp>\n" +
                "          <stringProp name=\"JSONPathExtractor.defaultValues\">EXTRACTION_FAILED</stringProp>\n" +
                "          <stringProp name=\"JSONPathExtractor.match_no\">0</stringProp>\n" +
                "        </JSONPathExtractor>\n" +
                "        <hashTree/>\n";
    }

    private String xpathExtractor(CorrelationDecision d) {
        return "        <XPathExtractor guiclass=\"XPathExtractorGui\" testclass=\"XPathExtractor\" testname=\"Extract: " + esc(d.getVariableName()) + "\" enabled=\"true\">\n" +
                "          <stringProp name=\"XPathExtractor.default\">EXTRACTION_FAILED</stringProp>\n" +
                "          <stringProp name=\"XPathExtractor.refname\">" + esc(d.getVariableName()) + "</stringProp>\n" +
                "          <stringProp name=\"XPathExtractor.xpathQuery\">" + esc(d.getExtractorExpression()) + "</stringProp>\n" +
                "          <boolProp name=\"XPathExtractor.validate\">false</boolProp>\n" +
                "          <boolProp name=\"XPathExtractor.tolerant\">false</boolProp>\n" +
                "          <boolProp name=\"XPathExtractor.namespace\">false</boolProp>\n" +
                "        </XPathExtractor>\n" +
                "        <hashTree/>\n";
    }

    private String boundaryExtractor(CorrelationDecision d) {
        String[] parts = d.getExtractorExpression().split("\\|\\|", 2);
        String left = parts.length > 0 ? parts[0] : "";
        String right = parts.length > 1 ? parts[1] : "";
        return "        <BoundaryExtractor guiclass=\"BoundaryExtractorGui\" testclass=\"BoundaryExtractor\" testname=\"Extract: " + esc(d.getVariableName()) + "\" enabled=\"true\">\n" +
                "          <stringProp name=\"BoundaryExtractor.useHeaders\">false</stringProp>\n" +
                "          <stringProp name=\"BoundaryExtractor.refname\">" + esc(d.getVariableName()) + "</stringProp>\n" +
                "          <stringProp name=\"BoundaryExtractor.lboundary\">" + esc(left) + "</stringProp>\n" +
                "          <stringProp name=\"BoundaryExtractor.rboundary\">" + esc(right) + "</stringProp>\n" +
                "          <stringProp name=\"BoundaryExtractor.default\">EXTRACTION_FAILED</stringProp>\n" +
                "          <stringProp name=\"BoundaryExtractor.match_no\">1</stringProp>\n" +
                "        </BoundaryExtractor>\n" +
                "        <hashTree/>\n";
    }

    private String groovyExtractor(CorrelationDecision d) {
        return "        <JSR223PostProcessor guiclass=\"TestBeanGUI\" testclass=\"JSR223PostProcessor\" testname=\"Extract: " + esc(d.getVariableName()) + "\" enabled=\"true\">\n" +
                "          <stringProp name=\"scriptLanguage\">groovy</stringProp>\n" +
                "          <stringProp name=\"script\">" + esc(d.getExtractorExpression()) + "</stringProp>\n" +
                "        </JSR223PostProcessor>\n" +
                "        <hashTree/>\n";
    }

    private String viewResultsTree() {
        return "      <ResultCollector guiclass=\"ViewResultsFullVisualizer\" testclass=\"ResultCollector\" testname=\"View Results Tree\" enabled=\"true\">\n" +
                "        <boolProp name=\"ResultCollector.error_logging\">false</boolProp>\n" +
                "        <objProp><name>saveConfig</name><value class=\"SampleSaveConfiguration\"/></objProp>\n" +
                "        <stringProp name=\"filename\"></stringProp>\n" +
                "      </ResultCollector>\n" +
                "      <hashTree/>\n";
    }

    private String summaryReport() {
        return "      <ResultCollector guiclass=\"SummaryReport\" testclass=\"ResultCollector\" testname=\"Summary Report\" enabled=\"true\">\n" +
                "        <boolProp name=\"ResultCollector.error_logging\">false</boolProp>\n" +
                "        <objProp><name>saveConfig</name><value class=\"SampleSaveConfiguration\"/></objProp>\n" +
                "        <stringProp name=\"filename\">results.jtl</stringProp>\n" +
                "      </ResultCollector>\n" +
                "      <hashTree/>\n";
    }

    private String hashTreeOpen() { return "    <hashTree>\n"; }
    private String hashTreeClose() { return "    </hashTree>\n"; }
    private String jmeterTestPlanClose() { return "</jmeterTestPlan>\n"; }

    // ─── Helpers ───────────────────────────────────────────────────────────────

    private Map<String, List<CorrelationDecision>> groupByEntry(List<CorrelationDecision> decisions) {
        Map<String, List<CorrelationDecision>> map = new HashMap<>();
        for (CorrelationDecision d : decisions) {
            map.computeIfAbsent(d.getExtractionEntryIndex(), k -> new ArrayList<>()).add(d);
        }
        return map;
    }

    private String applySubstitutions(String text, int currentEntryIdx, List<CorrelationDecision> decisions) {
        if (text == null) return "";
        String result = text;
        for (CorrelationDecision d : decisions) {
            if (d.shouldSkip()) continue;
            String originalValue = d.getDynamicValue().getValue();
            int sourceIdx = Integer.parseInt(d.getExtractionEntryIndex());
            if (sourceIdx < currentEntryIdx && result.contains(originalValue)) {
                result = result.replace(originalValue, "${" + d.getVariableName() + "}");
            }
        }
        return result;
    }

    private String extractBaseDomain(List<HARModel.Entry> entries) {
        if (entries.isEmpty()) return "";
        try {
            URI uri = new URI(entries.get(0).request.url);
            return uri.getScheme() + "://" + uri.getHost()
                    + (uri.getPort() > 0 ? ":" + uri.getPort() : "");
        } catch (Exception e) { return ""; }
    }

    private boolean isCommonHeader(String name) {
        if (name == null) return false;
        String n = name.toLowerCase();
        return n.equals("accept") || n.equals("accept-language") || n.equals("accept-encoding")
                || n.equals("user-agent") || n.equals("connection");
    }

    private boolean isImportantHeader(String name) {
        if (name == null) return false;
        String n = name.toLowerCase();
        return n.equals("content-type") || n.equals("authorization") || n.contains("token")
                || n.contains("csrf") || n.equals("x-requested-with");
    }

    private String esc(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&apos;");
    }
}
